using Model.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDataPopulator
{
    internal static class VerbsToPopulate
    {
        internal static (
            string? sp_DisplayName,
            string  sp_Conjugator,
            string  sp_Infinitive,
            string? sp_Core1,
            string? sp_Core2,
            string? sp_Core3,
            string? sp_Core4,
            string? sp_Gerund,
            string? sp_PastParticiple,
            string? en_DisplayName,
            string  en_Conjugator,
            string  en_Infinitive,
            string? en_Core1,
            string? en_Core2,
            string? en_Core3,
            string? en_Core4,
            string? en_Gerund,
            string? en_PastParticiple
            )[] verbs = [
("abandonar", "_Ar","abandonar","abandon",null,null,null,"abandonando","abandonado","to leave","EnglishVerbTranslator","to leave","leave","left","leaves",null,"leaving","left"),
("abordar", "_Ar","abordar","abord",null,null,null,"abordando","abordado","to board","EnglishVerbTranslator","to board","board","boarded","boards",null,"boarding","boarded"),
("abordar", "_Ar","abordar","abord",null,null,null,"abordando","abordado","to tackle","EnglishVerbTranslator","to tackle","tackle","tackled","tackles",null,"tackling","tackled"),
("abortar", "_Ar","abortar","abort",null,null,null,"abortando","abortado","to abort","EnglishVerbTranslator","to abort","abort","aborted","aborts",null,"aborting","aborted"),
("abortar", "_Ar","abortar","abort",null,null,null,"abortando","abortado","to foil","EnglishVerbTranslator","to foil","foil","foiled","foils",null,"foiling","foiled"),
("abrir", "_Ir","abrir","abr",null,null,null,"abriendo","abierto","to open","EnglishVerbTranslator","to open","open","opened","opens",null,"opening","opened"),
("abusar", "_Ar","abusar","abus",null,null,null,"abusando","abusado","to abuse","EnglishVerbTranslator","to abuse","abuse","abuseed","abuses",null,"abuseing","abuseed"),
("acabar", "_Ar","acabar","acab",null,null,null,"acabando","acabado","to end","EnglishVerbTranslator","to end","end","ended","ends",null,"ending","ended"),
("acabar", "_Ar","acabar","acab",null,null,null,"acabando","acabado","to finish","EnglishVerbTranslator","to finish","finish","finished","finishes",null,"finishing","finished"),
("acampar", "_Ar","acampar","acamp",null,null,null,"acampando","acampado","to camp","EnglishVerbTranslator","to camp","camp","camped","camps",null,"camping","camped"),
("aceptar", "_Ar","aceptar","acept",null,null,null,"aceptando","aceptado","to accept","EnglishVerbTranslator","to accept","accept","accepted","accepts",null,"accepting","accepted"),
("acompañar", "_Ar","acompañar","acompañ",null,null,null,"acompañando","acompañado","to accompany","EnglishVerbTranslator","to accompany","accompany","accompanyed","accompanys",null,"accompanying","accompanyed"),
("aconsejar", "_Ar","aconsejar","aconsej",null,null,null,"aconsejando","aconsejado","to advise","EnglishVerbTranslator","to advise","advise","advised","advises",null,"advising","advised"),
("acordar", "_Cordar","acordar","acord","acuerd",null,null,"acordando","acordado","to agree","EnglishVerbTranslator","to agree","agree","agreed","agrees",null,"agreeing","agreed"),
("acortar", "_Ar","acortar","acort",null,null,null,"acortando","acortado","to shorten","EnglishVerbTranslator","to shorten","shorten","shortened","shortens",null,"shortening","shortened"),
("acostumbrar", "_Ar","acostumbrar","acostumbr",null,null,null,"acostumbrando","acostumbrado","to accustom","EnglishVerbTranslator","to accustom","accustom","accustomed","accustoms",null,"accustoming","accustomed"),
("adivinar", "_Ar","adivinar","adivin",null,null,null,"adivinando","adivinado","to guess","EnglishVerbTranslator","to guess","guess","guessed","guesses",null,"guessing","guessed"),
("adivinar", "_Ar","adivinar","adivin",null,null,null,"adivinando","adivinado","to predict","EnglishVerbTranslator","to predict","predict","predicted","predicts",null,"predicting","predicted"),
("admirar", "_Ar","admirar","admir",null,null,null,"admirando","admirado","to admire","EnglishVerbTranslator","to admire","admire","admired","admires",null,"admiring","admired"),
("adorar", "_Ar","adorar","ador",null,null,null,"adorando","adorado","to adore","EnglishVerbTranslator","to adore","adore","adored","adores",null,"adoring","adored"),
("adorar", "_Ar","adorar","ador",null,null,null,"adorando","adorado","to worship","EnglishVerbTranslator","to worship","worship","worshipped","worships",null,"worshiping","worshipped"),
("afirmar", "_Ar","afirmar","afirm",null,null,null,"afirmando","afirmado","to affirm","EnglishVerbTranslator","to affirm","affirm","affirmed","affirms",null,"affirming","affirmed"),
("andar", "Andar","andar","and",null,null,null,"andando","andado","to walk","EnglishVerbTranslator","to walk","walk","walked","walks",null,"walking","walked"),
("añadir", "_Ir","añadir","añad",null,null,null,"añadiendo","añadido","to add","EnglishVerbTranslator","to add","add","added","adds",null,"adding","added"),
("apoyar", "_Ar","apoyar","apoy",null,null,null,"apoyando","apoyado","to support","EnglishVerbTranslator","to support","support","supported","supports",null,"supporting","supported"),
("apreciar", "_Ar","apreciar","apreci",null,null,null,"apreciando","apreciado","to appreciate","EnglishVerbTranslator","to appreciate","appreciate","appreciated","appreciates",null,"appreciating","appreciated"),
("apreciar", "_Ar","apreciar","apreci",null,null,null,"apreciando","apreciado","to value","EnglishVerbTranslator","to value","value","valued","values",null,"valuing","valued"),
("aprender", "_Er","aprender","aprend",null,null,null,"aprendiendo","aprendido","to learn","EnglishVerbTranslator","to learn","learn","learned","learns",null,"learning","learned"),
("arreglar", "_Ar","arreglar","arregl",null,null,null,"arreglando","arreglado","to fix","EnglishVerbTranslator","to fix","fix","fixed","fixes",null,"fixing","fixed"),
("arreglar", "_Ar","arreglar","arregl",null,null,null,"arreglando","arreglado","to repair","EnglishVerbTranslator","to repair","repair","repaired","repairs",null,"repairing","repaired"),
("asistir", "_Ir","asistir","asist",null,null,null,"asistiendo","asistido","to assist","EnglishVerbTranslator","to assist","assist","assisted","assists",null,"assisting","assisted"),
("asistir", "_Ir","asistir","asist",null,null,null,"asistiendo","asistido","to attend","EnglishVerbTranslator","to attend","attend","attended","attends",null,"attending","attended"),
("aumentar", "_Ar","aumentar","aument",null,null,null,"aumentando","aumentado","to increase","EnglishVerbTranslator","to increase","increase","increased","increases",null,"increasing","increased"),
("ayudar", "_Ar","ayudar","ayud",null,null,null,"ayudando","ayudado","to help","EnglishVerbTranslator","to help","help","helped","helps",null,"helping","helped"),
("bailar", "_Ar","bailar","bail",null,null,null,"bailando","bailado","to dance","EnglishVerbTranslator","to dance","dance","danced","dances",null,"dancing","danced"),
("bajar", "_Ar","bajar","baj",null,null,null,"bajando","bajado","to lower","EnglishVerbTranslator","to lower","lower","lowered","lowers",null,"lowering","lowered"),
("bañar", "_Ar","bañar","bañ",null,null,null,"bañando","bañado","to bathe","EnglishVerbTranslator","to bathe","bathe","bathed","bathes",null,"batheing","bathed"),
("bastar", "_Ar","bastar","bast",null,null,null,"bastando","bastado","to suffice","EnglishVerbTranslator","to suffice","suffice","sufficed","suffices",null,"sufficing","sufficed"),
("bastar", "_Ar","bastar","bast",null,null,null,"bastando","bastado","to be enough","EnglishVerbTranslator","to be enough","be enough","was enough","is enough",null,"is being enough","been enough"),
("beber", "_Er","beber","beb",null,null,null,"bebiendo","bebido","to drink","EnglishVerbTranslator","to drink","drink","drank","drinks",null,"drinking","drunken"),
("buscar", "_Car","buscar","busc","busqu",null,null,"buscando","buscado","to look for","EnglishVerbTranslator","to look for","look for","looked for","looks for",null,"looking for","looked for"),
("caer", "Caer","caer","ca",null,null,null,"cayendo","caído","to fall","EnglishVerbTranslator","to fall","fall","fell","falls",null,"falling","fallen"),
("callar", "_Ar","callar","call",null,null,null,"callando","callado","to keep quiet","EnglishVerbTranslator","to keep quiet","keep quiet","kept quiet","keeps quiet",null,"keeping quiet","kept quiet"),
("cambiar", "_Ar","cambiar","cambi",null,null,null,"cambiando","cambiado","to change","EnglishVerbTranslator","to change","change","changed","changes",null,"changing","changed"),
("caminar", "_Ar","caminar","camin",null,null,null,"caminando","caminado","to walk","EnglishVerbTranslator","to walk","walk","walked","walks",null,"walking","walked"),
("caminar", "_Ar","caminar","camin",null,null,null,"caminando","caminado","to go","EnglishVerbTranslator","to go","go","went","goes",null,"going","gone"),
("casar", "_Ar","casar","cas",null,null,null,"casando","casado","to marry","EnglishVerbTranslator","to marry","marry","married","marries",null,"marrying","married"),
("celebrar", "_Ar","celebrar","celebr",null,null,null,"celebrando","celebrado","to celebrate","EnglishVerbTranslator","to celebrate","celebrate","celebrated","celebrates",null,"celebrating","celebrated"),
("cerrar", "Cerrar","cerrar","cerr","cierr",null,null,"cerrando","cerrado","to close","EnglishVerbTranslator","to close","close","closed","closes",null,"closing","closed"),
("cocinar", "_Ar","cocinar","cocin",null,null,null,"cocinando","cocinado","to cook","EnglishVerbTranslator","to cook","cook","cooked","cooks",null,"cooking","cooked"),
("combatir", "_Ir","combatir","combat",null,null,null,"combatiendo","combatido","to combat","EnglishVerbTranslator","to combat","combat","combatted","combats",null,"combatting","combatted"),
("combatir", "_Ir","combatir","combat",null,null,null,"combatiendo","combatido","to fight","EnglishVerbTranslator","to fight","fight","fought","fights",null,"fighting","fought"),
("comer", "_Er","comer","com",null,null,null,"comiendo","comido","to eat","EnglishVerbTranslator","to eat","eat","ate","eats",null,"eating","eaten"),
("compartir", "_Ir","compartir","compart",null,null,null,"compartiendo","compartido","to share","EnglishVerbTranslator","to share","share","shared","shares",null,"sharing","shared"),
("comprar", "_Ar","comprar","compr",null,null,null,"comprando","comprado","to buy","EnglishVerbTranslator","to buy","buy","bought","buys",null,"buying","bought"),
("comprar", "_Ar","comprar","compr",null,null,null,"comprando","comprado","to purchase","EnglishVerbTranslator","to purchase","purchase","purchased","purchases",null,"purchasing","purchased"),
("comprender", "_Er","comprender","comprend",null,null,null,"comprendiendo","comprendido","to understand","EnglishVerbTranslator","to understand","understand","understood","understands",null,"understanding","understood"),
("conocer", "_Cer","conocer","conoc","conozc",null,null,"conociendo","conocido","to know","EnglishVerbTranslator","to know","know","knew","knows",null,"knowing","knew"),
("conseguir", "Seguir","conseguir","consegu","consig","consigu",null,"consiguiendo","conseguido","to get","EnglishVerbTranslator","to get","get","got","gets",null,"geting","gotten"),
("conservar", "_Ar","conservar","conserv",null,null,null,"conservando","conservado","to conserve","EnglishVerbTranslator","to conserve","conserve","conserved","conserves",null,"conserving","conserved"),
("conservar", "_Ar","conservar","conserv",null,null,null,"conservando","conservado","to preserve","EnglishVerbTranslator","to preserve","preserve","preserved","preserves",null,"preserving","preserved"),
("construir", "_Ir","construir","constru",null,null,null,"construiendo","construido","to build","EnglishVerbTranslator","to build","build","built","builds",null,"building","built"),
("construir", "_Ir","construir","constru",null,null,null,"construiendo","construido","to construct","EnglishVerbTranslator","to construct","construct","constructed","constructs",null,"constructing","constructed"),
("contar", "_Cordar","contar","cont","cuent",null,null,"contando","contado","to count","EnglishVerbTranslator","to count","count","counted","counts",null,"counting","counted"),
("contribuir", "_Ir","contribuir","contribu",null,null,null,"contribuiendo","contribuido","to contribute","EnglishVerbTranslator","to contribute","contribute","contributed","contributes",null,"contributing","contributed"),
("controlar", "_Ar","controlar","control",null,null,null,"controlando","controlado","to control","EnglishVerbTranslator","to control","control","controlled","controls",null,"controlling","controlled"),
("correr", "_Er","correr","corr",null,null,null,"corriendo","corrido","to run","EnglishVerbTranslator","to run","run","ran","runs",null,"runing","run"),
("cortar", "_Ar","cortar","cort",null,null,null,"cortando","cortado","to cut","EnglishVerbTranslator","to cut","cut","cut","cuts",null,"cutting","cut"),
("costar", "_Cordar","costar","cost","cuest",null,null,"costando","costado","to cost","EnglishVerbTranslator","to cost","cost","cost","costs",null,"costing","cost"),
("creer", "Creer","creer","cre","crey",null,null,"creyendo","creído","to believe","EnglishVerbTranslator","to believe","believe","believed","believes",null,"believing","believed"),
("cubrir", "_Ir","cubrir","cubr",null,null,null,"cubriendo","cubrido","to cover","EnglishVerbTranslator","to cover","cover","covered","covers",null,"covering","covered"),
("cuidar", "_Ar","cuidar","cuid",null,null,null,"cuidando","cuidado","to take care of","EnglishVerbTranslator","to take care of","take care of","took care of","takes care of",null,"taking care of","taken care of"),
("dar", "Dar","dar","d",null,null,null,"dando","dado","to give","EnglishVerbTranslator","to give","give","gave","gives",null,"giving","given"),
("deber", "_Er","deber","deb",null,null,null,"debiendo","debido","must","InvariableVerbTranslator","must","must","must have","must",null,"must","must have"),
("deber", "_Er","deber","deb",null,null,null,"debiendo","debido","should","InvariableVerbTranslator","should","should","should have","should",null,"should","should have"),
("deber", "_Er","deber","deb",null,null,null,"debiendo","debido","to owe","EnglishVerbTranslator","to owe","owe","owed","owes",null,"oweing","owed"),
("decidir", "_Ir","decidir","decid",null,null,null,"decidiendo","decidido","to decide","EnglishVerbTranslator","to decide","decide","decided","decides",null,"deciding","decided"),
("decir", "Decir","decir","dec","dig","dij",null,"diciendo","dicho","to say","EnglishVerbTranslator","to say","say","said","says",null,"saying","said"),
("declarar", "_Ar","declarar","declar",null,null,null,"declarando","declarado","to declare","EnglishVerbTranslator","to declare","declare","declared","declares",null,"declaring","declared"),
("dejar", "_Ar","dejar","dej",null,null,null,"dejando","dejado","to leave","EnglishVerbTranslator","to leave","leave","left","leaves",null,"leaving","left"),
("desarrollar", "_Ar","desarrollar","desarroll",null,null,null,"desarrollando","desarrollado","to develop","EnglishVerbTranslator","to develop","develop","developed","develops",null,"developing","developed"),
("desarrollar", "_Ar","desarrollar","desarroll",null,null,null,"desarrollando","desarrollado","to expand","EnglishVerbTranslator","to expand","expand","expanded","expands",null,"expanding","expanded"),
("descubrir", "_Ir","descubrir","descubr",null,null,null,"descubriendo","descubrido","to discover","EnglishVerbTranslator","to discover","discover","discovered","discovers",null,"discovering","discovered"),
("desear", "_Ar","desear","dese",null,null,null,"deseando","deseado","to desire","EnglishVerbTranslator","to desire","desire","desired","desires",null,"desiring","desired"),
("desear", "_Ar","desear","dese",null,null,null,"deseando","deseado","to want","EnglishVerbTranslator","to want","want","wanted","wants",null,"wanting","wanted"),
("disculpar", "_Ar","disculpar","disculp",null,null,null,"disculpando","disculpado","to forgive","EnglishVerbTranslator","to forgive","forgive","forgave","forgives",null,"forgiven","forgave"),
("disfrutar", "_Ar","disfrutar","disfrut",null,null,null,"disfrutando","disfrutado","to enjoy","EnglishVerbTranslator","to enjoy","enjoy","enjoyed","enjoys",null,"enjoying","enjoyed"),
("distinguir", "_Ir","distinguir","distingu",null,null,null,"distinguiendo","distinguido","to distinguish","EnglishVerbTranslator","to distinguish","distinguish","distinguished","distinguishes",null,"distinguishing","distinguished"),
("doler", "Mover","doler","dol","duel",null,null,"doliendo","dolido","to hurt","EnglishVerbTranslator","to hurt","hurt","hurt","hurts",null,"hurting","hurt"),
("dormir", "Dormir","dormir","dorm","duerm","durm",null,"durmiendo","dormido","to sleep","EnglishVerbTranslator","to sleep","sleep","slept","sleeps",null,"sleeping","slept"),
("echar", "_Ar","echar","ech",null,null,null,"echando","echado","to cast","EnglishVerbTranslator","to cast","cast","cast","casts",null,"casting","cast"),
("echar", "_Ar","echar","ech",null,null,null,"echando","echado","to throw","EnglishVerbTranslator","to throw","throw","threw","throws",null,"throwing","thrown"),
("ejercer", "_Er","ejercer","ejerc",null,null,null,"ejerciendo","ejercido","to exercise","EnglishVerbTranslator","to exercise","exercise","exercised","exercises",null,"exercising","exercised"),
("ejercer", "_Er","ejercer","ejerc",null,null,null,"ejerciendo","ejercido","to practice","EnglishVerbTranslator","to practice","practice","practiced","practices",null,"practicing","practiced"),
("eliminar", "_Ar","eliminar","elimin",null,null,null,"eliminando","eliminado","to eliminate","EnglishVerbTranslator","to eliminate","eliminate","eliminated","eliminates",null,"eliminating","eliminated"),
("eliminar", "_Ar","eliminar","elimin",null,null,null,"eliminando","eliminado","to remove","EnglishVerbTranslator","to remove","remove","removed","removes",null,"removing","removed"),
("empezar", "Empezar","empezar","empez","empec","empiez","empiec","empezando","empezado","to start","EnglishVerbTranslator","to start","start","started","starts",null,"starting","started"),
("encantar", "_Ar","encantar","encant",null,null,null,"encantando","encantado","to delight in","EnglishVerbTranslator","to delight in","delight in","delighted in","delights in",null,"delighting in","delighted in"),
("encantar", "_Ar","encantar","encant",null,null,null,"encantando","encantado","to enchant","EnglishVerbTranslator","to enchant","enchant","enchanted","enchants",null,"enchanting","enchanted"),
("encantar", "_Ar","encantar","encant",null,null,null,"encantando","encantado","to love","EnglishVerbTranslator","to love","love","loved","loves",null,"loving","loved"),
("encontrar", "_Cordar","encontrar","encontr","encuentr",null,null,"encontrando","encontrado","to find","EnglishVerbTranslator","to find","find","found","finds",null,"finding","found"),
("entender", "Perder","entender","entend","entiend",null,null,"entendiendo","entendido","to understand","EnglishVerbTranslator","to understand","understand","understood","understands",null,"understanding","understood"),
("entrar", "_Ar","entrar","entr",null,null,null,"entrando","entrado","to enter","EnglishVerbTranslator","to enter","enter","entered","enters",null,"entering","entered"),
("escribir", "_Ir","escribir","escrib",null,null,null,"escribiendo","escribido","to write","EnglishVerbTranslator","to write","write","wrote","writes",null,"writing","written"),
("escuchar", "_Ar","escuchar","escuch",null,null,null,"escuchando","escuchado","to hear","EnglishVerbTranslator","to hear","hear","heard","hears",null,"hearing","heard"),
("escuchar", "_Ar","escuchar","escuch",null,null,null,"escuchando","escuchado","to listen to","EnglishVerbTranslator","to listen to","listen to","listened to","listens to",null,"listening to","listened to"),
("esperar", "_Ar","esperar","esper",null,null,null,"esperando","esperado","to hope","EnglishVerbTranslator","to hope","hope","hoped","hopes",null,"hoping","hoped"),
("esperar", "_Ar","esperar","esper",null,null,null,"esperando","esperado","to wait","EnglishVerbTranslator","to wait","wait","waited","waits",null,"waiting","waited"),
("estar", "Estar","estar","est",null,null,null,"estando","estado","to be","EnglishVerbTranslator","to be","be","was","is",null,"being","been"),
("estudiar", "_Ar","estudiar","estudi",null,null,null,"estudiando","estudiado","to study","EnglishVerbTranslator","to study","study","studied","studies",null,"studying","studied"),
("evitar", "_Ar","evitar","evit",null,null,null,"evitando","evitado","to avoid","EnglishVerbTranslator","to avoid","avoid","avoided","avoids",null,"avoiding","avoided"),
("existir", "_Ir","existir","exist",null,null,null,"existiendo","existido","to exist","EnglishVerbTranslator","to exist","exist","existed","exists",null,"existing","existed"),
("explicar", "_Car","explicar","explic","expliqu",null,null,"explicando","explicado","to explain","EnglishVerbTranslator","to explain","explain","explained","explains",null,"explaining","explained"),
("expresar", "_Ar","expresar","expres",null,null,null,"expresando","expresado","to express","EnglishVerbTranslator","to express","express","expressed","expresses",null,"expressing","expressed"),
("expresar", "_Ar","expresar","expres",null,null,null,"expresando","expresado","to state","EnglishVerbTranslator","to state","state","stated","states",null,"stating","stated"),
("faltar", "_Ar","faltar","falt",null,null,null,"faltando","faltado","to fail","EnglishVerbTranslator","to fail","fail","failed","fails",null,"failing","failed"),
("faltar", "_Ar","faltar","falt",null,null,null,"faltando","faltado","to lack","EnglishVerbTranslator","to lack","lack","lacked","lacks",null,"lacking","lacked"),
("formar", "_Ar","formar","form",null,null,null,"formando","formado","to form","EnglishVerbTranslator","to form","form","formed","forms",null,"forming","formed"),
("formar", "_Ar","formar","form",null,null,null,"formando","formado","to shape","EnglishVerbTranslator","to shape","shape","shaped","shapes",null,"shaping","shaped"),
("funcionar", "_Ar","funcionar","funcion",null,null,null,"funcionando","funcionado","to function","EnglishVerbTranslator","to function","function","functioned","functions",null,"functioning","functioned"),
("funcionar", "_Ar","funcionar","funcion",null,null,null,"funcionando","funcionado","to work","EnglishVerbTranslator","to work","work","worked","works",null,"working","worked"),
("ganar", "_Ar","ganar","gan",null,null,null,"ganando","ganado","to earn","EnglishVerbTranslator","to earn","earn","earned","earns",null,"earning","earned"),
("ganar", "_Ar","ganar","gan",null,null,null,"ganando","ganado","to gain","EnglishVerbTranslator","to gain","gain","gained","gains",null,"gaining","gained"),
("ganar", "_Ar","ganar","gan",null,null,null,"ganando","ganado","to win","EnglishVerbTranslator","to win","win","won","wins",null,"winning","won"),
("guardar", "_Ar","guardar","guard",null,null,null,"guardando","guardado","to guard","EnglishVerbTranslator","to guard","guard","guarded","guards",null,"guarding","guarded"),
("guardar", "_Ar","guardar","guard",null,null,null,"guardando","guardado","to put away","EnglishVerbTranslator","to put away","put away","put away","puts away",null,"putting away","put away"),
("gustar", "_Ar","gustar","gust",null,null,null,"gustando","gustado","to like","EnglishVerbTranslator","to like","like","liked","likes",null,"liking","liked"),
("gustar", "_Ar","gustar","gust",null,null,null,"gustando","gustado","to love","EnglishVerbTranslator","to love","love","loved","loves",null,"loving","loved"),
("Haber (aux)", "HaberHave","haber","hab",null,null,null,"habiendo","habido","to have","EnglishVerbTranslator","to have","have","had","has",null,"having","had"),
("Haber (hay)", "HaberThereIs","haber","hab",null,null,null,null,null,"there is","EnglishVerbTranslator","there is","there is","there was","there is",null,"there is","there was"),
("hablar", "_Ar","hablar","habl",null,null,null,"hablando","hablado","to speak","EnglishVerbTranslator","to speak","speak","spoke","speaks",null,"speaking","spoken"),
("hacer", "Hacer","hacer","hac","hag","hic","hiz","haciendo","hecho","to do","EnglishVerbTranslator","to do","do","did","does",null,"doing","done"),
("hacer", "Hacer","hacer","hac","hag","hic","hiz","haciendo","hecho","to make","EnglishVerbTranslator","to make","make","made","makes",null,"making","made"),
("imaginar", "_Ar","imaginar","imagin",null,null,null,"imaginando","imaginado","to imagine","EnglishVerbTranslator","to imagine","imagine","imagined","imagines",null,"imagining","imagined"),
("importar", "_Ar","importar","import",null,null,null,"importando","importado","to import","EnglishVerbTranslator","to import","import","imported","imports",null,"importing","imported"),
("incluir", "_Ir","incluir","inclu",null,null,null,"incluiendo","incluido","to include","EnglishVerbTranslator","to include","include","included","includes",null,"including","included"),
("informar", "_Ar","informar","inform",null,null,null,"informando","informado","to inform","EnglishVerbTranslator","to inform","inform","informed","informs",null,"informing","informed"),
("informar", "_Ar","informar","inform",null,null,null,"informando","informado","to report","EnglishVerbTranslator","to report","report","reported","reports",null,"reporting","reported"),
("iniciar", "_Ar","iniciar","inici",null,null,null,"iniciando","iniciado","to start","EnglishVerbTranslator","to start","start","started","starts",null,"starting","started"),
("insistir", "_Ir","insistir","insist",null,null,null,"insistiendo","insistido","to insist","EnglishVerbTranslator","to insist","insist","insisted","insists",null,"insisting","insisted"),
("intentar", "_Ar","intentar","intent",null,null,null,"intentando","intentado","to try","EnglishVerbTranslator","to try","try","tried","tries",null,"trying","tried"),
("interesar", "_Ar","interesar","interes",null,null,null,"interesando","interesado","to appeal","EnglishVerbTranslator","to appeal","appeal","appealed","appeals",null,"appealing","appealed"),
("interesar", "_Ar","interesar","interes",null,null,null,"interesando","interesado","to interest","EnglishVerbTranslator","to interest","interest","interested","interests",null,"interesting","interested"),
("interpretar", "_Ar","interpretar","interpret",null,null,null,"interpretando","interpretado","to interpret","EnglishVerbTranslator","to interpret","interpret","interpreted","interprets",null,"interpreting","interpreted"),
("ir", "Ir","ir",null,null,null,null,"yendo","ido","to go","EnglishVerbTranslator","to go","go","went","goes",null,"going","gone"),
("jugar", "Jugar","jugar","jug","juegu","jueg","jugu","jugando","jugado","to play","EnglishVerbTranslator","to play","play","played","plays",null,"playing","played"),
("jurar", "_Ar","jurar","jur",null,null,null,"jurando","jurado","to promise","EnglishVerbTranslator","to promise","promise","promised","promises",null,"promising","promised"),
("jurar", "_Ar","jurar","jur",null,null,null,"jurando","jurado","to swear","EnglishVerbTranslator","to swear","swear","sweared","swears",null,"swearing","sworn"),
("largar", "_Gar","largar","larg","largu",null,null,"largando","largado","to pay out","EnglishVerbTranslator","to pay out","pay out","paid out","pays out",null,"paying out","paid out"),
("levantar", "_Ar","levantar","levant",null,null,null,"levantando","levantado","to raise","EnglishVerbTranslator","to raise","raise","raised","raises",null,"raising","raised"),
("levantar", "_Ar","levantar","levant",null,null,null,"levantando","levantado","to lift up","EnglishVerbTranslator","to lift up","lift up","lifted up","lifts up",null,"lifting up","lifted up"),
("llamar", "_Ar","llamar","llam",null,null,null,"llamando","llamado","to call","EnglishVerbTranslator","to call","call","called","calls",null,"calling","called"),
("llamar", "_Ar","llamar","llam",null,null,null,"llamando","llamado","to name","EnglishVerbTranslator","to name","name","named","names",null,"naming","named"),
("llegar", "_Gar","llegar","lleg","llegu",null,null,"llegando","llegado","to arrive","EnglishVerbTranslator","to arrive","arrive","arrived","arrives",null,"arriving","arrived"),
("llenar", "_Ar","llenar","llen",null,null,null,"llenando","llenado","to fill","EnglishVerbTranslator","to fill","fill","filled","fills",null,"filling","filled"),
("llevar", "_Ar","llevar","llev",null,null,null,"llevando","llevado","to bring","EnglishVerbTranslator","to bring","bring","brought","brings",null,"bringing","brought"),
("llevar", "_Ar","llevar","llev",null,null,null,"llevando","llevado","to carry","EnglishVerbTranslator","to carry","carry","carried","carries",null,"carrying","carried"),
("llevar", "_Ar","llevar","llev",null,null,null,"llevando","llevado","to take","EnglishVerbTranslator","to take","take","took","takes",null,"taking","taken"),
("llevar", "_Ar","llevar","llev",null,null,null,"llevando","llevado","to wear","EnglishVerbTranslator","to wear","wear","wore","wears",null,"wearing","worn"),
("llorar", "_Ar","llorar","llor",null,null,null,"llorando","llorado","to cry","EnglishVerbTranslator","to cry","cry","cried","cries",null,"crying","cried"),
("llorar", "_Ar","llorar","llor",null,null,null,"llorando","llorado","to mourn","EnglishVerbTranslator","to mourn","mourn","mourned","mourns",null,"mourning","mourned"),
("llorar", "_Ar","llorar","llor",null,null,null,"llorando","llorado","to weep","EnglishVerbTranslator","to weep","weep","wept","weeps",null,"weeping","wept"),
("lograr", "_Ar","lograr","logr",null,null,null,"logrando","logrado","to achieve","EnglishVerbTranslator","to achieve","achieve","achieved","achieves",null,"achieving","achieved"),
("luchar", "_Ar","luchar","luch",null,null,null,"luchando","luchado","to fight","EnglishVerbTranslator","to fight","fight","fought","fights",null,"fighting","fought"),
("luchar", "_Ar","luchar","luch",null,null,null,"luchando","luchado","to struggle","EnglishVerbTranslator","to struggle","struggle","struggled","struggles",null,"struggling","struggled"),
("mandar", "_Ar","mandar","mand",null,null,null,"mandando","mandado","to command","EnglishVerbTranslator","to command","command","commanded","commands",null,"commanding","commanded"),
("mandar", "_Ar","mandar","mand",null,null,null,"mandando","mandado","to order","EnglishVerbTranslator","to order","order","ordered","orders",null,"ordering","ordered"),
("mandar", "_Ar","mandar","mand",null,null,null,"mandando","mandado","to send","EnglishVerbTranslator","to send","send","sent","sends",null,"sending","sent"),
("manejar", "_Ar","manejar","manej",null,null,null,"manejando","manejado","to handle","EnglishVerbTranslator","to handle","handle","handled","handles",null,"handling","handled"),
("manejar", "_Ar","manejar","manej",null,null,null,"manejando","manejado","to manage","EnglishVerbTranslator","to manage","manage","managed","manages",null,"managing","managed"),
("mantener", "Mantener","mantener","manten","mantien","mantuv","manteng","manteniendo","mantenido","to hold","EnglishVerbTranslator","to hold","hold","held","holds",null,"holding","held"),
("matar", "_Ar","matar","mat",null,null,null,"matando","matado","to kill","EnglishVerbTranslator","to kill","kill","killed","kills",null,"killing","killed"),
("meter", "_Er","meter","met",null,null,null,"metiendo","metido","to insert","EnglishVerbTranslator","to insert","insert","inserted","inserts",null,"inserting","inserted"),
("meter", "_Er","meter","met",null,null,null,"metiendo","metido","to put","EnglishVerbTranslator","to put","put","put","puts",null,"puting","put"),
("mirar", "_Ar","mirar","mir",null,null,null,"mirando","mirado","to look at","EnglishVerbTranslator","to look at","look at","looked at","looks at",null,"looking at","looked at"),
("mirar", "_Ar","mirar","mir",null,null,null,"mirando","mirado","to see","EnglishVerbTranslator","to see","see","seeed","sees",null,"seeing","seeed"),
("mirar", "_Ar","mirar","mir",null,null,null,"mirando","mirado","to watch","EnglishVerbTranslator","to watch","watch","watched","watches",null,"watching","watched"),
("morir", "Dormir","morir","mor","muer","mur",null,"muriendo","muerto","to die","EnglishVerbTranslator","to die","die","died","dies",null,"dying","died"),
("mover", "Mover","mover","mov","muev",null,null,"moviendo","movido","to move","EnglishVerbTranslator","to move","move","moved","moves",null,"moving","moved"),
("necesitar", "_Ar","necesitar","necesit",null,null,null,"necesitando","necesitado","to need","EnglishVerbTranslator","to need","need","needed","needs",null,"needing","needed"),
("necesitar", "_Ar","necesitar","necesit",null,null,null,"necesitando","necesitado","to require","EnglishVerbTranslator","to require","require","required","requires",null,"requiring","required"),
("negociar", "_Ar","negociar","negoci",null,null,null,"negociando","negociado","to negotiate","EnglishVerbTranslator","to negotiate","negotiate","negotiated","negotiates",null,"negotiating","negotiated"),
("notar", "_Ar","notar","not",null,null,null,"notando","notado","to notice","EnglishVerbTranslator","to notice","notice","noticed","notices",null,"noticing","noticed"),
("notar", "_Ar","notar","not",null,null,null,"notando","notado","to notice","EnglishVerbTranslator","to notice","notice","noticeed","notices",null,"noticeing","noticeed"),
("notar", "_Ar","notar","not",null,null,null,"notando","notado","to observe","EnglishVerbTranslator","to observe","observe","observed","observes",null,"observing","observed"),
("notar", "_Ar","notar","not",null,null,null,"notando","notado","to remark","EnglishVerbTranslator","to remark","remark","remarked","remarks",null,"remarking","remarked"),
("obrar", "_Ar","obrar","obr",null,null,null,"obrando","obrado","to act","EnglishVerbTranslator","to act","act","acted","acts",null,"acting","acted"),
("ocurrir", "_Ir","ocurrir","ocurr",null,null,null,"ocurriendo","ocurrido","to happen","EnglishVerbTranslator","to happen","happen","happened","happens",null,"happening","happened"),
("oír", "Oir","oír","o","oig","oy",null,"oyendo","oído","to hear","EnglishVerbTranslator","to hear","hear","heard","hears",null,"hearing","heard"),
("oír", "Oir","oír","o","oig","oy",null,"oyendo","oído","to listen to","EnglishVerbTranslator","to listen to","listen to","listened to","listens to",null,"listening to","listened to"),
("olvidar", "_Ar","olvidar","olvid",null,null,null,"olvidando","olvidado","to forget","EnglishVerbTranslator","to forget","forget","forgot","forgets",null,"forgetting","forgotten"),
("olvidar", "_Ar","olvidar","olvid",null,null,null,"olvidando","olvidado","to neglect","EnglishVerbTranslator","to neglect","neglect","neglected","neglects",null,"neglecting","neglected"),
("pagar", "_Gar","pagar","pag","pagu",null,null,"pagando","pagado","to pay for","EnglishVerbTranslator","to pay for","pay for","paid for","pays for",null,"paying for","paid for"),
("parar", "_Ar","parar","par",null,null,null,"parando","parado","to halt","EnglishVerbTranslator","to halt","halt","halted","halts",null,"halting","halted"),
("parar", "_Ar","parar","par",null,null,null,"parando","parado","to stop","EnglishVerbTranslator","to stop","stop","stopped","stops",null,"stopping","stopped"),
("parecer", "_Cer","parecer","parec","parezc",null,null,"pareciendo","parecido","to seem","EnglishVerbTranslator","to seem","seem","seemed","seems",null,"seeming","seemed"),
("participar", "_Ar","participar","particip",null,null,null,"participando","participado","to participate","EnglishVerbTranslator","to participate","participate","participated","participates",null,"participating","participated"),
("partir", "_Ir","partir","part",null,null,null,"partiendo","partido","to cut","EnglishVerbTranslator","to cut","cut","cut","cuts",null,"cutting","cut"),
("partir", "_Ir","partir","part",null,null,null,"partiendo","partido","to split","EnglishVerbTranslator","to split","split","split","splits",null,"splitting","split"),
("pasar", "_Ar","pasar","pas",null,null,null,"pasando","pasado","to happen","EnglishVerbTranslator","to happen","happen","happened","happens",null,"happening","happened"),
("pasar", "_Ar","pasar","pas",null,null,null,"pasando","pasado","to pass","EnglishVerbTranslator","to pass","pass","passed","passes",null,"passing","passed"),
("pasar", "_Ar","pasar","pas",null,null,null,"pasando","pasado","to pass by","EnglishVerbTranslator","to pass by","pass by","passed by","passes by",null,"passing by","passed by"),
("pedir", "Pedir","pedir","ped","pid",null,null,"pidiendo","pedido","to ask for","EnglishVerbTranslator","to ask for","ask for","asked for","asks for",null,"asking for","asked for"),
("pedir", "Pedir","pedir","ped","pid",null,null,"pidiendo","pedido","to order","EnglishVerbTranslator","to order","order","ordered","orders",null,"ordering","ordered"),
("pensar", "Cerrar","pensar","pens","piens",null,null,"pensando","pensado","to think","EnglishVerbTranslator","to think","think","thought","thinks",null,"thinking","thought"),
("perder", "Perder","perder","perd","pierd",null,null,"perdiendo","perdido","to lose","EnglishVerbTranslator","to lose","lose","lost","loses",null,"losing","lost"),
("perdonar", "_Ar","perdonar","perdon",null,null,null,"perdonando","perdonado","to excuse","EnglishVerbTranslator","to excuse","excuse","excused","excuses",null,"excusing","excused"),
("perdonar", "_Ar","perdonar","perdon",null,null,null,"perdonando","perdonado","to forgive","EnglishVerbTranslator","to forgive","forgive","forgave","forgives",null,"forgiving","forgiven"),
("perdonar", "_Ar","perdonar","perdon",null,null,null,"perdonando","perdonado","to pardon","EnglishVerbTranslator","to pardon","pardon","pardoned","pardons",null,"pardoning","pardoned"),
("permitir", "_Ir","permitir","permit",null,null,null,"permitiendo","permitido","to permit","EnglishVerbTranslator","to permit","permit","permitted","permits",null,"permitting","permitted"),
("permitir", "_Ir","permitir","permit",null,null,null,"permitiendo","permitido","to allow","EnglishVerbTranslator","to allow","allow","allowed","allows",null,"allowing","allowed"),
("pesar", "_Ar","pesar","pes",null,null,null,"pesando","pesado","to weigh","EnglishVerbTranslator","to weigh","weigh","weighed","weighs",null,"weighing","weighed"),
("poder", "Poder","poder","pod","pued","pud",null,"pudiendo","podido","to be able to","EnglishVerbTranslator","to be able to","be able to","was able to","is able to",null,"being able to","been able to"),
("poner", "Poner","poner","pon","pus",null,null,"poniendo","puesto","to put","EnglishVerbTranslator","to put","put","put","puts",null,"putting","put"),
("preferir", "Preferir","preferir","prefer","prefier","prefir",null,"prefiriendo","preferido","to prefer","EnglishVerbTranslator","to prefer","prefer","preferred","prefers",null,"preferring","preferred"),
("preguntar", "_Ar","preguntar","pregunt",null,null,null,"preguntando","preguntado","to ask","EnglishVerbTranslator","to ask","ask","asked","asks",null,"asking","asked"),
("preocupar", "_Ar","preocupar","preocup",null,null,null,"preocupando","preocupado","to worry","EnglishVerbTranslator","to worry","worry","worried","worries",null,"worrying","worried"),
("preparar", "_Ar","preparar","prepar",null,null,null,"preparando","preparado","to prepare","EnglishVerbTranslator","to prepare","prepare","prepared","prepares",null,"preparing","prepared"),
("preparar", "_Ar","preparar","prepar",null,null,null,"preparando","preparado","to get ready","EnglishVerbTranslator","to get ready","get ready","got ready","gets ready",null,"getting ready","gotten ready"),
("presentar", "_Ar","presentar","present",null,null,null,"presentando","presentado","to present","EnglishVerbTranslator","to present","present","presented","presents",null,"presenting","presented"),
("prometer", "_Er","prometer","promet",null,null,null,"prometiendo","prometido","to promise","EnglishVerbTranslator","to promise","promise","promised","promises",null,"promising","promised"),
("proteger", "_Er","proteger","proteg",null,null,null,"protegiendo","protegido","to protect","EnglishVerbTranslator","to protect","protect","protected","protects",null,"protecting","protected"),
("quedar", "_Ar","quedar","qued",null,null,null,"quedando","quedado","to remain","EnglishVerbTranslator","to remain","remain","remained","remains",null,"remaining","remained"),
("querer", "Querer","querer","quer","quier","quis","querr","queriendo","querido","to want","EnglishVerbTranslator","to want","want","wanted","wants",null,"wanting","wanted"),
("querer", "Querer","querer","quer","quier","quis","querr","queriendo","querido","to love","EnglishVerbTranslator","to love","love","loved","loves",null,"loving","loved"),
("realizar", "_Zar","realizar","realiz","realic",null,null,"realizando","realizado","to carry out","EnglishVerbTranslator","to carry out","carry out","carried out","carries out",null,"carrying out","carried out"),
("recibir", "_Ir","recibir","recib",null,null,null,"recibiendo","recibido","to receive","EnglishVerbTranslator","to receive","receive","received","receives",null,"receiving","received"),
("recoger", "_Er","recoger","recog",null,null,null,"recogiendo","recogido","to pick up","EnglishVerbTranslator","to pick up","pick up","picked up","picks up",null,"picking up","picked up"),
("recoger", "_Er","recoger","recog",null,null,null,"recogiendo","recogido","to collect","EnglishVerbTranslator","to collect","collect","collected","collects",null,"collecting","collected"),
("recordar", "_Cordar","recordar","record","recuerd",null,null,"recordando","recordado","to remember","EnglishVerbTranslator","to remember","remember","remembered","remembers",null,"remembering","remembered"),
("regalar", "_Ar","regalar","regal",null,null,null,"regalando","regalado","to give a present","EnglishVerbTranslator","to give a present","give a present","gave a present","gives a present",null,"giving a present","given a present"),
("regresar", "_Ar","regresar","regres",null,null,null,"regresando","regresado","to return","EnglishVerbTranslator","to return","return","returned","returns",null,"returning","returned"),
("regresar", "_Ar","regresar","regres",null,null,null,"regresando","regresado","to go back","EnglishVerbTranslator","to go back","go back","went back","goes back",null,"going back","gone back"),
("renunciar", "_Ar","renunciar","renunci",null,null,null,"renunciando","renunciado","to renounce","EnglishVerbTranslator","to renounce","renounce","renounced","renounces",null,"renouncing","renounced"),
("respetar", "_Ar","respetar","respet",null,null,null,"respetando","respetado","to respect","EnglishVerbTranslator","to respect","respect","respected","respects",null,"respecting","respected"),
("responder", "_Er","responder","respond",null,null,null,"respondiendo","respondido","to respond to","EnglishVerbTranslator","to respond to","respond to","responded to","responds to",null,"responding to","responded to"),
("responder", "_Er","responder","respond",null,null,null,"respondiendo","respondido","to answer","EnglishVerbTranslator","to answer","answer","answered","answers",null,"answering","answered"),
("responder", "_Er","responder","respond",null,null,null,"respondiendo","respondido","to reply","EnglishVerbTranslator","to reply","reply","replied","replies",null,"replying","replied"),
("resultar", "_Ar","resultar","result",null,null,null,"resultando","resultado","to prove to be","EnglishVerbTranslator","to prove to be","prove to be","proved to be","proves to be",null,"proving to be","proven to be"),
("resultar", "_Ar","resultar","result",null,null,null,"resultando","resultado","to turn out to be","EnglishVerbTranslator","to turn out to be","turn out to be","turned out to be","turns out to be",null,"turning out to be","turned out to be"),
("rezar", "_Zar","rezar","rez","rec",null,null,"rezando","rezado","to pray","EnglishVerbTranslator","to pray","pray","prayed","prays",null,"praying","prayed"),
("romper", "_Er","romper","romp",null,null,null,"rompiendo","rompido","to break","EnglishVerbTranslator","to break","break","broke","breaks",null,"breaking","broken"),
("saber", "Saber","saber","sab","sep","sup",null,"sabiendo","sabido","to know","EnglishVerbTranslator","to know","know","knew","knows",null,"knowing","known"),
("sacar", "_Car","sacar","sac","saqu",null,null,"sacando","sacado","to take out","EnglishVerbTranslator","to take out","take out","took out","takes out",null,"taking out","taken out"),
("salir", "Salir","salir","sal","salg",null,null,"saliendo","salido","to go out","EnglishVerbTranslator","to go out","go out","go out","goes out",null,"going out","gone out"),
("salvar", "_Ar","salvar","salv",null,null,null,"salvando","salvado","to save","EnglishVerbTranslator","to save","save","saved","saves",null,"saving","saved"),
("salvar", "_Ar","salvar","salv",null,null,null,"salvando","salvado","to rescue","EnglishVerbTranslator","to rescue","rescue","rescued","rescues",null,"rescuing","rescued"),
("seguir", "Seguir","seguir","segu","sig","sigu",null,"siguiendo","seguido","to follow","EnglishVerbTranslator","to follow","follow","followed","follows",null,"following","followed"),
("sentir", "Sentir","sentir","sent","sient","sint",null,"sintiendo","sentido","to feel","EnglishVerbTranslator","to feel","feel","felt","feels",null,"feeling","felt"),
("señalar", "_Ar","señalar","señal",null,null,null,"señalando","señalado","to show","EnglishVerbTranslator","to show","show","showed","shows",null,"showing","shown"),
("ser", "Ser","ser","s","er","so","fu","siendo","sido","to be","EnglishVerbTranslator","to be","be","was","is",null,"being","been"),
("servir", "Pedir","servir","serv","sirv",null,null,"sirviendo","servido","to be useful","EnglishVerbTranslator","to be useful","be useful","was useful","is useful",null,"is being useful","has been useful"),
("servir", "Pedir","servir","serv","sirv",null,null,"sirviendo","servido","to serve","EnglishVerbTranslator","to serve","serve","served","serves",null,"serving","served"),
("significar", "_Car","significar","signific","signifiqu",null,null,"significando","significado","to mean","EnglishVerbTranslator","to mean","mean","meant","means",null,"meaning","meant"),
("sonar", "_Cordar","sonar","son","suen",null,null,"sonando","sonado","to ring","EnglishVerbTranslator","to ring","ring","ringed","rings",null,"ringing","ringed"),
("soñar", "_Cordar","soñar","soñ","sueñ",null,null,"soñando","soñado","to dream","EnglishVerbTranslator","to dream","dream","dreamed","dreams",null,"dreaming","dreamed"),
("subir", "_Ir","subir","sub",null,null,null,"subiendo","subido","to climb","EnglishVerbTranslator","to climb","climb","climbed","climbs",null,"climbing","climbed"),
("subir", "_Ir","subir","sub",null,null,null,"subiendo","subido","to go up","EnglishVerbTranslator","to go up","go up","went up","goes up",null,"going up","gone up"),
("subir", "_Ir","subir","sub",null,null,null,"subiendo","subido","to move up","EnglishVerbTranslator","to move up","move up","moved up","moves up",null,"moving up","moved up"),
("subir", "_Ir","subir","sub",null,null,null,"subiendo","subido","to rise","EnglishVerbTranslator","to rise","rise","rose","rises",null,"rising","risen"),
("suceder", "_Er","suceder","suced",null,null,null,"sucediendo","sucedido","to happen to","EnglishVerbTranslator","to happen to","happen to","happened to","happens to",null,"happening to","happened to"),
("suceder", "_Er","suceder","suced",null,null,null,"sucediendo","sucedido","to follow","EnglishVerbTranslator","to follow","follow","followed","follows",null,"following","followed"),
("suceder", "_Er","suceder","suced",null,null,null,"sucediendo","sucedido","to succeed","EnglishVerbTranslator","to succeed","succeed","succeeded","succeeds",null,"succeeding","succeeded"),
("sufrir", "_Ir","sufrir","sufr",null,null,null,"sufriendo","sufrido","to suffer","EnglishVerbTranslator","to suffer","suffer","suffered","suffers",null,"suffering","suffered"),
("suponer", "Suponer","suponer","supon","supus",null,null,"suponiendo","supuesto","to suppose","EnglishVerbTranslator","to suppose","suppose","supposed","supposes",null,"suposing","supposed"),
("tener", "Tener","tener","ten","tien","tuv","teng","teniendo","tenido","to have","EnglishVerbTranslator","to have","have","had","has",null,"having","had"),
("terminar", "_Ar","terminar","termin",null,null,null,"terminando","terminado","to end","EnglishVerbTranslator","to end","end","ended","ends",null,"ending","ended"),
("terminar", "_Ar","terminar","termin",null,null,null,"terminando","terminado","to finish","EnglishVerbTranslator","to finish","finish","finished","finishes",null,"finishing","finished"),
("tirar", "_Ar","tirar","tir",null,null,null,"tirando","tirado","to fire (a weapon)","EnglishVerbTranslator","to fire (a weapon)","fire (a weapon)","fired (a weapon)","fires (a weapon)",null,"firing (a weapon)","fired (a weapon)"),
("tirar", "_Ar","tirar","tir",null,null,null,"tirando","tirado","to get rid of","EnglishVerbTranslator","to get rid of","get rid of","got rid of","gets rid of",null,"getting rid of","gotten rid of"),
("tirar", "_Ar","tirar","tir",null,null,null,"tirando","tirado","to hurl","EnglishVerbTranslator","to hurl","hurl","hurled","hurls",null,"hurling","hurled"),
("tirar", "_Ar","tirar","tir",null,null,null,"tirando","tirado","to launch","EnglishVerbTranslator","to launch","launch","launched","launches",null,"launching","launched"),
("tirar", "_Ar","tirar","tir",null,null,null,"tirando","tirado","to throw","EnglishVerbTranslator","to throw","throw","threw","throws",null,"throwing","thrown"),
("tocar", "_Car","tocar","toc","toqu",null,null,"tocando","tocado","to touch","EnglishVerbTranslator","to touch","touch","touched","touches",null,"touching","touched"),
("tomar", "_Ar","tomar","tom",null,null,null,"tomando","tomado","to drink","EnglishVerbTranslator","to drink","drink","drank","drinks",null,"drinking","drunken"),
("tomar", "_Ar","tomar","tom",null,null,null,"tomando","tomado","to take","EnglishVerbTranslator","to take","take","took","takes",null,"taking","taken"),
("trabajar", "_Ar","trabajar","trabaj",null,null,null,"trabajando","trabajado","to work","EnglishVerbTranslator","to work","work","worked","works",null,"working","worked"),
("traer", "Traer","traer","tra","traig","traj",null,"trayendo","traído","to bring","EnglishVerbTranslator","to bring","bring","brought","brings",null,"bringing","brought"),
("tratar", "_Ar","tratar","trat",null,null,null,"tratando","tratado","to handle","EnglishVerbTranslator","to handle","handle","handled","handles",null,"handling","handled"),
("tratar", "_Ar","tratar","trat",null,null,null,"tratando","tratado","to treat","EnglishVerbTranslator","to treat","treat","treated","treats",null,"treating","treated"),
("usar", "_Ar","usar","us",null,null,null,"usando","usado","to use","EnglishVerbTranslator","to use","use","used","uses",null,"useing","used"),
("valer", "Valer","valer","val","valg",null,null,"valiendo","valido","to be worth","EnglishVerbTranslator","to be worth","be worth","was worth","is worth",null,"being worth","been worth"),
("valer", "Valer","valer","val","valg",null,null,"valiendo","valido","to cost","EnglishVerbTranslator","to cost","cost","cost","costs",null,"costing","cost"),
("vencer", "_Er","vencer","venc",null,null,null,"venciendo","vencido","to conquer","EnglishVerbTranslator","to conquer","conquer","conquered","conquers",null,"conquering","conquered"),
("vender", "_Er","vender","vend",null,null,null,"vendiendo","vendido","to sell","EnglishVerbTranslator","to sell","sell","sold","sells",null,"selling","sold"),
("venir", "Venir","venir","ven","vien","vin",null,"viniendo","venido","to come","EnglishVerbTranslator","to come","come","came","comes",null,"coming","come"),
("ver", "Ver","ver","v","ve",null,null,"viendo","visto","to see","EnglishVerbTranslator","to see","see","saw","sees",null,"seeing","seen"),
("ver", "Ver","ver","v","ve",null,null,"viendo","visto","to watch","EnglishVerbTranslator","to watch","watch","watched","watches",null,"watching","watched"),
("vestir", "Pedir","vestir","vest","vist",null,null,"vistiendo","vestido","to wear","EnglishVerbTranslator","to wear","wear","wore","wears",null,"wearing","worn"),
("vestir", "Pedir","vestir","vest","vist",null,null,"vistiendo","vestido","to dress","EnglishVerbTranslator","to dress","dress","dressed","dresses",null,"dressing","dressed"),
("viajar", "_Ar","viajar","viaj",null,null,null,"viajando","viajado","to travel","EnglishVerbTranslator","to travel","travel","traveled","travels",null,"traveling","traveled"),
("visitar", "_Ar","visitar","visit",null,null,null,"visitando","visitado","to visit","EnglishVerbTranslator","to visit","visit","visited","visits",null,"visiting","visited"),
("vivir", "_Ir","vivir","viv",null,null,null,"viviendo","vivido","to live","EnglishVerbTranslator","to live","live","lived","lives",null,"living","lived"),
("volver", "Mover","volver","volv","vuelv",null,null,"volviendo","vuelto","to return","EnglishVerbTranslator","to return","return","returned","returns",null,"returning","returned"),

            ];
    }
}
